upstream sv_usuarios {
    server sv-usuarios:3000;
}

upstream sv_publicacoes {
    server sv-publicacoes:3000;
}

upstream sv_match {
    server sv-match:3000;
}

upstream sv_notificacao {
    server sv-notificacao:3000;
}

server {
    listen 80;
    server_name localhost;

    location /api/users {
        rewrite ^/api(.*)$ $1 break;
        proxy_pass http://sv_usuarios;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/publicacoes {
        rewrite ^/api(.*)$ $1 break;
        proxy_pass http://sv_publicacoes;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/match {
        rewrite ^/api(.*)$ $1 break;
        proxy_pass http://sv_match;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/notificacoes {
        rewrite ^/api(.*)$ $1 break;
        proxy_pass http://sv_notificacao;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /socket.io {
        proxy_pass http://sv_notificacao;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 60s;
    }
}
